---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.flask: glob:staging-*
  name: flask
  namespace: default
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: flask
      containers:
      - image: umairedu/flask:staging-hwsoer1c
        name: flask
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.postgres: glob:10.4-*
  name: postgres
  namespace: default
