---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.podinfod: semver:~1.7
  name: podinfo
  namespace: demo
spec:
  template:
    spec:
      $setElementOrder/initContainers:
      - name: init
      initContainers:
      - image: alpine:20190925
        name: init
