---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:staging-*
  name: flask
  namespace: default
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: flask
      containers:
      - image: umairedu/flask:staging-m5oka5pd
        name: flask
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:11.*
  name: postgres
  namespace: default
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: postgres
      containers:
      - image: postgres:10-alpine
        name: postgres
