---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:v*
  name: flask
  namespace: default
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: flask
      - name: flaskd
      containers:
      - image: umairedu/flask:v4
        name: flask
      - image: umairedu/flask:v4
        name: flaskd
