---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:dev-*
  name: umair
  namespace: demo
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: umair
      $setElementOrder/initContainers:
      - name: init
      containers:
      - image: umairedu/podinfo:dev-wn29qffi
        name: umair
      initContainers:
      - image: alpine:20190925
        name: init
