apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: default
spec:
  encryptedData:
    password: AgAA+IZ0twSW7YVXo8OF2b/lIeeeUTWR73Vym/Cbdn6H8hvrpsAP9kQiN5PXzIiD8uVDdu1S0xL5o6QtT5GwQK7A/AVIdSoATmuiZ6mQ47P2lVbw1nrym/dPEUgAoS+3vmuv9yxAG+ZcpY4fKOPH4KV2cFHyn7l45qHhRHM2lyDRXG5C+luEvhl1DFEzsflGJ+ABTd9xKTyxzrMrYjogMIWm95mcKseinU72NXl7s4M4qvuJAML7+NFo4u9Zt1bsOsuUs2Kx0kt62xai4mB2ES1mZbyau/QSelw7hFZjCe0A6uzAap6DDSI8BBvgzbQQ181hkTAIZ6T1Nnm8ZSpEw1aMSrRoJU0iY3V1hsBlbJOdB/oKhNg1sa8FlMWOUYKlchbXEcjZ0dKOlkGO8Q5ohYg+uDU6QtZHY/vePQM79jfTbbohjV7vUYdhdoHZ60cXRhnyMi6aQqMfEirXAoHQ+yMBEj2kSYCrqWhGpKaeV3JwHlxjrBUyJux7Dr2phwNtODoLWsf+N++FyNrjLW9U0WL8nCXMaCHeAp2w2WRbK2Am5PPvGv4siJ7o8WNeWkLub4ibAmEYx3BqQcP12oEid8NiIErf+avyXOo0ucOJtYBgaODn7fGticqJbxP38tzmqK9JbHiSLKUO2WkoEQunIepEVcdGlGSzMafRcMj8TDnJKr1YhyimUSeMDF6VDTL+CaKf0+A=
    user: AgBOBXyF0wJFAGhYpKx/ycIBvPLwo0xbpZ6KDEtjfi/pqbXH9JLIWZv1uS6QCOrgxRCr/qieYHMo7kgJ21Q8+9DXzauAmpqNphbl+NPq26eOPSs6KuEjK9ahh1BVG3hX9VnOty3MIRGOQqiS8OGhAIkY5W8MEPkwUVrPnwc1sWsiXC3afXOwte4p+lsAzIsuVkwxPOjdgK3VTsfIJ75HffCCvSiYdpZOJApBghfJBjPUuPHdxV3/i7GNc2OQZD+LZDQWQgi4Ayoq6YHkPABRyh/8I8/Gfo5vwSFDS6L/B1Zl586gHeSxiHDjYbmSwyUFkIqBdjr/1YD8nL4JpnhAtz86sJvSs2ZUbR+AyE9Y2vqU38SyS54SKI0QlPqKt4z+vIhRWaFbFfYrCCrR9ht7IzSaCQ3+RGjd5gZqhGs4Ki02Ec7dvSjNvtdPifXgNZxRoJqTKlRGx32bFew2OMfWwtAC8SdlOqFWGb1Wek2FSsdt1VYC0Cd6EGSYobg/ULwMGuXrO3jpGp++Y+cC+x0N4oR0lRoabCiXjGVya+QZqTSM/BnQEBT3zROTAYPEStd144l+mp7aLzaQzPdBw+vlf3x9XVO3MygV1Zk6YyAzwgJ30a8NPPZ6AA464CVob7wgeZCxK8wdH9BZLQtawwqYuxwx2iUxPBgtySWGGYZKM/74wvIJBBmNV4O32bxmE0zyBT053OWnug==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: default
    type: Opaque
status: {}