---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: default
  labels:
    app: flask
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      annotations:
        prometheus.io/port: "5000"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: umairedu/flask:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: flask_UI_COLOR
          value: green
        livenessProbe:
          httpGet:
            path: /books
            port: 5000
        readinessProbe:
          httpGet:
            path: /books
            port: 5000
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
