apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvcv2
  namespace: default
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: postgres-datav2
  storageClassName: standard