apiVersion: v1
kind: Service
metadata:
  name: flask
  namespace: default
  labels:
    app: flask
spec:
  type: NodePort
  selector:
    app: flask
  ports:
  - name: flask
    port: 5000
    targetPort: 5000
