---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: umair
  namespace: demo
  labels:
    app: umair
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: umair
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: umair
    spec:
      initContainers:
      - name: init
        image: alpine:3.9
        command:
        - sleep
        - "1"
      containers:
      - name: umair
        image: umairedu/podinfo:dev-0n29qffi
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9898
          name: http
          protocol: TCP
        command:
        - ./podinfo
        - --port=9898
        - --level=info
        - --random-delay=false
        - --random-error=false
        env:
        - name: PODINFO_UI_COLOR
          value: green
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9898
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9898
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
